cmake_minimum_required(VERSION 3.5)
project(texcup2bag)
set(CMAKE_CXX_FLAGS "-std=c++17")
set(CMAKE_CXX_FLAGS_RELEASE "-O2")
find_package(catkin REQUIRED COMPONENTS roscpp rosbag gnss_comm)
catkin_package()
include_directories(${catkin_INCLUDE_DIRS})
add_executable(rinex2bag src/rinex2bag.cpp)
target_link_libraries(rinex2bag ${catkin_LIBRARIES})
